import type { Metadata } from "next";
import Link from "next/link";
import { SikiMascot } from "@/components/SikiMascot";

export const metadata: Metadata = {
  title: "Terms of Service — Sikizana Books",
  description: "Terms of service for Sikizana Books, the AI bookkeeper for Xero.",
};

/**
 * Terms of Service — required for the Xero App Store listing.
 * Honest terms for an AI bookkeeping assistant: what the service does,
 * what it doesn't promise, and the user's responsibilities.
 */
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-stone-100 flex flex-col">
      <nav className="bg-white border-b border-stone-200 px-4 py-3">
        <div className="max-w-6xl mx-auto flex items-center justify-between gap-2">
          <Link href="/" className="flex items-center gap-3">
            <SikiMascot size={36} mood="idle" />
            <div>
              <h1 className="text-base font-bold text-stone-900 leading-none">SIKIZANA BOOKS</h1>
              <p className="text-[10px] text-stone-500 leading-none mt-0.5">
                AI Bookkeeper for Xero
              </p>
            </div>
          </Link>
          <div className="flex items-center gap-2">
            <Link
              href="/privacy"
              className="text-xs text-stone-500 hover:text-stone-700 px-2 py-1 rounded hover:bg-stone-100 btn-press"
            >
              Privacy
            </Link>
            <Link
              href="/books"
              className="text-xs text-stone-500 hover:text-stone-700 px-2 py-1 rounded hover:bg-stone-100 btn-press"
            >
              Open Bookkeeper
            </Link>
          </div>
        </div>
      </nav>

      <div className="flex-1 max-w-2xl mx-auto w-full px-6 py-12">
        <h2 className="text-3xl font-bold text-stone-900 mb-2">Terms of Service</h2>
        <p className="text-xs text-stone-500 mb-8">Last updated: July 2026</p>

        <div className="space-y-8 text-sm text-stone-700 leading-relaxed">
          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">1. The service</h3>
            <p>
              Sikizana Books is an AI-powered bookkeeping assistant that connects to your Xero
              organisation. It reads your accounting data to answer questions, flag
              discrepancies, estimate taxes, and propose journal entries. By using the service
              you agree to these terms.
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">2. Not professional advice</h3>
            <p>
              Sikizana Books is a software tool, not an accountant, tax advisor, or financial
              advisor. Its answers — including tax estimates and proposed journal entries — are
              generated by AI and can be wrong or incomplete. Always verify important figures
              and consult a qualified professional before making tax filings or financial
              decisions based on the assistant&apos;s output.
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">3. Your responsibilities</h3>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                You must have the right to connect the Xero organisation you connect — either as
                its owner or with the owner&apos;s permission.
              </li>
              <li>
                You review every journal entry before approving it. Entries only post to Xero
                after your explicit approval, and you are responsible for what you approve.
              </li>
              <li>
                You keep your Xero login and this device secure; anyone with access to your
                browser session can see your connected data.
              </li>
            </ul>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">4. Demo mode</h3>
            <p>
              Without a connected Xero organisation the service runs on demo data. In demo mode,
              actions like posting a journal entry are simulated and clearly labelled as such —
              nothing is written to any real Xero organisation.
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">5. Third-party services</h3>
            <p>
              The service depends on Xero&apos;s API and on third-party AI providers (currently
              NVIDIA NIM and Google Gemini). Their availability affects ours, and their
              processing of your data is described in our{" "}
              <Link href="/privacy" className="text-sky-600 hover:text-sky-700 underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">6. Availability &amp; changes</h3>
            <p>
              The service is provided &quot;as is&quot;, without warranty of uninterrupted
              availability. We may change, suspend, or discontinue features. You can disconnect
              your Xero organisation at any time, which revokes our access to your data.
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">7. Limitation of liability</h3>
            <p>
              To the maximum extent permitted by law, Sikizana is not liable for indirect or
              consequential losses arising from use of the service, including losses caused by
              acting on AI-generated output without verification. Nothing in these terms limits
              liability that cannot be limited by law.
            </p>
          </section>

          <section>
            <h3 className="text-base font-semibold text-stone-900 mb-2">8. Contact</h3>
            <p>
              Questions about these terms? Email{" "}
              <a href="mailto:hello@sikizana.com" className="text-sky-600 hover:text-sky-700 underline">
                hello@sikizana.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>

      <footer className="border-t border-stone-200 bg-white">
        <div className="max-w-6xl mx-auto px-6 py-6 text-center">
          <div className="flex items-center justify-center gap-4 mb-2">
            <Link href="/privacy" className="text-xs text-stone-500 hover:text-stone-700 transition-colors">
              Privacy Policy
            </Link>
            <Link href="/terms" className="text-xs text-stone-500 hover:text-stone-700 transition-colors">
              Terms of Service
            </Link>
          </div>
          <p className="text-[10px] text-stone-400">
            Built for the Xero App &amp; Agent Hackathon · Encode Club · London 2026
          </p>
        </div>
      </footer>
    </main>
  );
}
